---
MetaArgs:
  global_seed: 1337
  num_runs: 5
  log_file_path: trade_rl.log
  experiment_name: buy_below_arrival
EnvironmentArgs:
  env_name: 'trade_rl/TradingEnvironment-v0'
  max_train_steps: 100000
  max_test_steps: 10000
  order_gen_args:
    sym_spec: ['TSLA']
    qty_spec: [10, 50]
    start_time_spec: [300, 1800, 9000, 18000] # 9:35, 10:00, 12:00, 2:30
    duration_spec: [60, 600, 3600] # 1 minute, 10 minutes, 1 hour duration
  feature_args:
    train_data_path: 'data/TSLA/OCHLV/train.parquet' # TODO: Multi-symbol
    test_data_path: 'data/TSLA/OCHLV/test.parquet' # TODO: Multi-symbol
    short_window: 5
    medium_window: 10
    long_window: 30
  reward_args:
    reward_type: 'arrival_sparse' # arrival_sparse, arrival_dense, vwap_sparse, vwap_dense, oracle
    termination_px_cost_multiplier: 1.5
AgentArgs:
  agent_type: 'buy_below_arrival' # random, buy_below_arrival, buy_last, buy_start, dqn, reinforce
  dqn_args:
    lr: 0.0002
    gamma: 0.99
    batch_size: 128
    buffer_size: 10000
    eps_start: 1.0
    eps_end: 0.05
  reinforce_args:
    lr: 0.01
    gamma: 0.99
    batch_size: 1000
    temp_start: 1.0
    temp_end: 0.05
