---
MetaArgs:
  global_seed: 1337
  log_file_path: trade_rl.log
  experiment_name: test_experiment
EnvironmentArgs:
  env_name: 'trade_rl/TradingEnvironment-v0'
  max_train_steps: 100000
  max_test_steps: 10000
  order_gen_args:
    sym_spec: ['TSLA']
    qty_spec: [10, 50]
    start_time_spec: [300, 1800, 9000, 18000] # 9:35, 10:00, 12:00, 2:30
    end_time_spec: [60, 600, 3600] # 1 minute, 10 minutes, 1 hour duration
