---
MetaArgs:
  global_seed: 1337
  log_file_path: trade_rl.log
  experiment_name: test_experiment
EnvironmentArgs:
  env_name: 'trade_rl/TradingEnvironment-v0'
  max_train_steps: 100000
  max_test_steps: 10000
  order_gen_args:
    sym_spec: ['TSLA']
    qty_spec: [10, 50]
    start_time_spec: [300, 1800, 9000, 18000] # 9:35, 10:00, 12:00, 2:30
    end_time_spec: [60, 600, 3600] # 1 minute, 10 minutes, 1 hour duration
AgentArgs:
  agent_type: 'random' # random, buy_below_arrival, buy_last, buy_start, linear, dqn, reinforce
  dqn_args:
    lr: 0.0002
    gamma: 0.99
    batch_size: 128
    buffer_size: 10000
    eps: 0.5 # TODO: Linear Schedule
  reinforce_args:
    lr: 0.01
    gamma: 0.99
    batch_size: 1000
    temp: 1 # TODO: Linear schedule
