---
MetaArgs:
  global_seed: 42
  num_runs: 1
  log_file_path: trade_rl.log
  experiment_name: TSLA/v2/dqn_agent_vwap_sparse
EnvironmentArgs:
  env_name: 'trade_rl/TradingEnvironment-v0'
  max_train_steps: 300000
  max_test_steps: 100000
  order_gen_args:
    sym_spec: ['TSLA']
    qty_spec: [0.1, 0.01] # Percentage of Order Duration
    start_time_spec: [1800, 7200, 12600] # 10:00, 11:30, 1:00
    duration_spec: [600, 3600, 10000] # 10 minutes, 1 hour, ~3 hours
  feature_args:
    train_data_path: 'data/TSLA/OCHLV/train.parquet' # TODO: Multi-symbol
    test_data_path: 'data/TSLA/OCHLV/test.parquet' # TODO: Multi-symbol
    short_window: 5
    medium_window: 10
    long_window: 30
  reward_args:
    reward_type: 'vwap_sparse' # arrival_sparse, arrival_dense, vwap_sparse, vwap_dense
    termination_px_cost_multiplier: 10
AgentArgs:
  agent_type: 'dqn' # random, buy_below_arrival, buy_last, buy_start, dqn, reinforce
  dqn_args:
    lr: 0.0002
    gamma: 0.99
    batch_size: 128
    buffer_size: 10000
    eps_start: 1.0
    eps_end: 0.05
  reinforce_args:
    lr: 0.01
    gamma: 0.99
    batch_size: 1000
    temp_start: 1.0
    temp_end: 0.05
